version: '2'

services:
  gittea:
    image: gitea/gitea:latest
    networks:
      - sonarnet
    ports: 
      - "3000:3000"
      - "222:22"
    environment: 
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always

  jenkins:
    image: jenkins/jenkins:lts
    volumes:
       - ./jenkins/data:/var/jenkins_home
    networks:
      - sonarnet
    ports:
      - '8080:8080'
      - '50000:50000'
    restart: always

  sonarqube:
    image: sonarqube:7.6-community 
    volumes:
      - ./sonarqube/conf/:/opt/sonarqube/conf
      - ./sonarqube/data/:/opt/sonarqube/data
      - ./sonarqube/extensions/:/opt/sonarqube/extensions
      - ./sonarqube/bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    networks:
      - sonarnet
    ports:
      - '9000:9000'
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      - sonar.jdbc.url=jdbc:postgresql://sonarqube_db:5432/sonar
    restart: always

  sonarqube_db:
    image: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - ./postgresql/:/var/lib/postgresql
      - ./postgresql/data/:/var/lib/postgresql/data
    restart: always

networks:
  sonarnet:
    driver: bridge